### ISSUE TITLE
Prompt and set Interval add-on  error in Browser again.

### ISSUE THREAD

**Issue by dedu6ka** [ankitest/anki-musthave-addons-by-ankitest#20]
The add-on works in Browser, too , but gives off this message.
In Reviewer, there is no message.

Traceback (most recent call last):
  File "C:\Users\Vit\Documents\Anki\addons\_Prompt_and_set_days_interval_and_card_ease.py", line 345, in <lambda>
    lambda s=self: resetSelectedCardScheduling(self))
  File "C:\Users\Vit\Documents\Anki\addons\_Prompt_and_set_days_interval_and_card_ease.py", line 331, in resetSelectedCardScheduling
    promptNewInterval(cids=cids)
  File "C:\Users\Vit\Documents\Anki\addons\_Prompt_and_set_days_interval_and_card_ease.py", line 253, in promptNewInterval
    SWAP_TAG += unicode(mw.reviewer.card.ord + 1)
AttributeError: 'NoneType' object has no attribute 'ord'

**Comment by ankitest** [comment]
This error has been fixed 06/12/2016.
