### ISSUE TITLE
' Again Good HUGE extra buttons conflict with multiple apps

### ISSUE THREAD

**Issue by smh020** [ankitest/anki-musthave-addons-by-ankitest#23]
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\webview.py", line 21, in link
  File "anki\hooks.py", line 55, in repl
  File "anki\hooks.py", line 55, in repl
  File "aqt\reviewer.py", line 319, in _linkHandler
  File "anki\hooks.py", line 61, in repl
  File "C:\Users\Steve\AppData\Roaming\Anki2\addons\image_occlusion_enhanced\main.py", line 406, in onShowAnswer
    return _old(self)
  File "C:\Users\Steve\AppData\Roaming\Anki2\addons\jsbooster\review_hack.py", line 78, in customShowAnswer
    a = self._mungeQA(a)
  File "aqt\reviewer.py", line 195, in _mungeQA
  File "C:\Users\Steve\AppData\Roaming\Anki2\addons\--musthave.py", line 8874, in myTypeAnsFilter
    return self.typeAnsAnswerFilter(buf, 0)
TypeError: maTypeAnsAnswerFilter() takes exactly 2 arguments (3 given)

**Comment by ankitest** [comment]
Thanks for bug report. I'll fix it ASAP.
